baseURL = 'https://houseofguineas.com'
languageCode = 'en-us'
title = 'House of Guineas'
theme = 'hugo-initio'
style = 'default'


[params]
name = "House of Guineas"
description = "San Francisco's exotic pet sitter"

email = "houseofguineas@gmail.com"
phone = "415-484-6493"
address = "San Francisco, CA"
year = 2024
avatar = "prof.jpeg"
avatarclass = "circle"
background = ""
banner = "milo.jpeg"
favicon = "images/gt_favicon.png"
DateForm = "January 2, 2006"
author = "Sergey Pozhilov (GetTemplate.com)"

showSubheader = true
showServices = true
showRecentWorks = true
# added reviews
showReviews = true
showDownloads = true
showClients = true

showFooterContact = true
showFooterFollowMe = true
showFooterTextWidget = false
showFooterFormWidget = false

[[menu.main]]
name = "home"
url = "/"
weight = 1
# [[menu.main]]
#  name = "blog"
#  url = "/post/"
# weight = 5

[params.disqus]
site = "hugo-initio-site.disqus.com"

[params.sharethis]
property = "123456789012345678901234"
custom = true

[params.google.analytics]
trackerID = "G-6JZQ3G0Q5M"

[[params.social]]
title = "tiktok"
url = "https://www.tiktok.com/@houseofguineas"
icon = "fa-brands fa-tiktok"
footer = true
sharethis = false
network = "tiktok"

[[params.social]]
title = "instagram"
url = "https://www.instagram.com/houseofguineas?igsh=OGQ5ZDc2ODk2ZA=="
icon = "fa-brands fa-instagram"
footer = true
sharethis = false
network = "instagram"

[[params.social]]
title = "youtube"
url = "https://www.youtube.com/@houseofguineas"
icon = "fa-brands fa-youtube"
footer = true
sharethis = false
network = "youtube"

[[params.social]]
title = "linkedin"
url = "https://www.linkedin.com/in/alexandria-b-65b845100/"
icon = "fa-brands fa-linkedin"
footer = true
sharethis = false
network = "linkedin"

[[params.social]]
title = "email"
url = "mailto:houseofguineas@gmail.com"
icon = "fa-regular fa-envelope"
footer = false
sharethis = false
network = "email"